name: visocr

networks:
  visocr-main:
    driver: bridge

services:
  demo:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    container_name: demo
    networks:
      - visocr-main
    ports:
      - 7860:7860