name: visocr-train

x-common-config:
  &common-config
  env_file:
    - .env
  networks:
    - visocr-main

networks:
  visocr-main:
    driver: bridge

volumes:
  postgres-data:
    driver: local

  minio-data:
    driver: local

  label-studio-data:
    driver: local

  redis-data:
    driver: local

services:
  postgres:
    <<: *common-config
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    <<: *common-config
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data

  minio-init:
    image: alpine:latest
    container_name: minio-init
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/init.sh:/minio/init.sh:ro
      - ./docker/configs.json:/minio/configs.json:ro
    entrypoint: ["/bin/sh", "/minio/init.sh"]
    depends_on:
      - minio
    networks:
      - visocr-main

  label-studio:
    <<: *common-config
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    environment:
      LOCAL_FILES_SERVING_ENABLED: true
      DJANGO_DB: default
      POSTGRE_NAME: labelstudio
      POSTGRE_USER: ${POSTGRES_USER}
      POSTGRE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRE_PORT: 5432
      POSTGRE_HOST: postgres
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_S3_REGION: us-east-1
      AWS_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - label-studio-data:/label-studio/data
      - ./docker/labelstudio:/label-studio/config
      - ./docker/configs.json:/label-studio/configs.json:ro
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - minio

  mlflow:
    <<: *common-config
    build:
      context: ./docker/mlflow
    container_name: mlflow
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/mlflow 
                    --default-artifact-root s3://mlflow/ 
                    --host 0.0.0.0
    networks:
      - visocr-main
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - minio

  redis:
    <<: *common-config
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prefect-server:
    <<: *common-config
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/prefect
      PREFECT_UI_API_URL: http://${APP_HOST}:4200/api
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging
      PREFECT_REDIS_MESSAGING_HOST: redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
      PREFECT_SERVER_API_AUTH_STRING: ${PREFECT_SERVER_USERNAME}:${PREFECT_SERVER_PASSWORD}
    command: prefect server start --no-services
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
  prefect-services:
    <<: *common-config
    image: prefecthq/prefect:3-latest
    container_name: prefect-services
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/prefect
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging
      PREFECT_REDIS_MESSAGING_HOST: redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
    networks:
      - visocr-main
    command: prefect server services start
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  prefect-worker:
    <<: *common-config
    image: prefecthq/prefect:3-latest
    container_name: prefect-worker
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_API_AUTH_STRING: ${PREFECT_SERVER_USERNAME}:${PREFECT_SERVER_PASSWORD}
    networks:
      - visocr-main
    command: prefect worker start --pool local-pool
    depends_on:
      prefect-server:
        condition: service_started
